List eventsList = [
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Monday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Monday',
    'time': '07:30 - 08:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '08:15 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Aerobics',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Chair based circuit',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '11:30 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '11:30 - 12:15',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '12:00 - 12:45',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Relax and Revive',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '13:30 - 14:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '14:15 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Monday',
    'time': '16:15 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Monday',
    'time': '17:00 - 17:30',
  },
  {
    'site': 'MDW',
    'name': 'Cardio Kick',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '18:30 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Boxercise',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '19:00 - 19:45',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '19:50 - 20:20',
  },
  {
    'site': 'MDW',
    'name': 'HIIT',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '20:00 - 20:45',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'Monday',
    'time': '20:30 - 21:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Tuesday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Tuesday',
    'time': '07:45 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '08:45 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '10:30 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '13:15 - 14:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '14:30 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '15:15 - 16:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '15:30 - 16:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Tuesday',
    'time': '16:30 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '17:15 - 17:45',
  },
  {
    'site': 'MDW',
    'name': 'Booty Build',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '18:00 - 18:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '18:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Legs, Bums & Tums',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '19:30 - 20:15',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '19:30 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '20:00 - 20:45',
  },
  {
    'site': 'MDW',
    'name': 'HIIT',
    'type': 'class',
    'info': '',
    'day': 'Tuesday',
    'time': '20:15 - 21:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Tuesday',
    'time': '21:15 - 21:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Wednesday',
    'time': '06:45 - 07:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual Sprint',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Wednesday',
    'time': '07:00 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '08:00 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '08:30 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Abs Blast',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '11:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '12:15 - 13:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '13:30 - 14:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '14:30 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '15:45 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Wednesday',
    'time': '16:30 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Wednesday',
    'time': '17:15 - 17:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Boxercise',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '19:00 - 19:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '19:30 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Dance Fit',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '19:45 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'Wednesday',
    'time': '20:30 - 21:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Thursday',
    'time': '06:45 - 07:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Thursday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '08:00 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual Sprint',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '08:00 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '09:15 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '10:15 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Padwork Circuit',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '11:15 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Relax and Revive',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '12:15 - 13:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '13:15 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '14:30 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Thursday',
    'time': '16:15 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '18:00 - 18:30',
  },
  {
    'site': 'MDW',
    'name': 'Cardio Kick',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '18:45 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit',
    'type': 'class',
    'info': '',
    'day': 'Thursday',
    'time': '19:30 - 20:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Thursday',
    'time': '20:20 - 21:05',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Thursday',
    'time': '21:10 - 21:40',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Friday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Friday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Friday',
    'time': '07:45 - 08:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '07:45 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '08:45 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '09:25 - 10:25',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '10:30 - 11:15',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '11:30 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '12:30 - 13:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '13:45 - 14:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '14:45 - 15:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '15:45 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '17:00 - 18:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'Friday',
    'time': '19:30 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Friday',
    'time': '20:40 - 21:10',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Saturday',
    'time': '08:15 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Advanced Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'Saturday',
    'time': '09:00 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit Strength',
    'type': 'class',
    'info': '',
    'day': 'Saturday',
    'time': '09:15 - 09:45',
  },
  {
    'site': 'MDW',
    'name': 'Baby Ballet',
    'type': 'class',
    'info': '',
    'day': 'Saturday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'Saturday',
    'time': '10:00 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit Plyo',
    'type': 'class',
    'info': '',
    'day': 'Saturday',
    'time': '10:35 - 11:05',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Saturday',
    'time': '11:30 - 12:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Saturday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Saturday',
    'time': '14:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Saturday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '09:00 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'Sunday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'Sunday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '11:45 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '12:45 - 13:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '13:00 - 13:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '14:00 - 14:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'Sunday',
    'time': '15:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': '60+ £1 Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Monday',
    'time': '06:30 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Monday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Monday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '09:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Fit',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Monday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Monday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '13:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Monday',
    'time': '15:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Monday',
    'time': '15:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '16:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '16:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Bootle and North Swim Club',
    'type': 'pool',
    'info': 'Main pool',
    'day': 'Monday',
    'time': '19:00 - 21:00',
  },
  {
    'site': 'MDW',
    'name': '2 Lane Triathlon',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '21:00 - 22:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Monday',
    'time': '21:00 - 22:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Tuesday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '06:30 - 08:00',
  },
  {
    'site': 'MDW',
    'name': 'Calm Waters',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '08:00 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Natal',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '09:00 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '09:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Tuesday',
    'time': '09:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Fit',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': '60+ £1 Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Tuesday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '13:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Tuesday',
    'time': '15:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '16:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Tuesday',
    'time': '16:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '16:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Fit',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Tuesday',
    'time': '20:00 - 20:45',
  },
  {
    'site': 'MDW',
    'name': '2 Lane Triathlon',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '20:45 - 21:45',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Tuesday',
    'time': '20:45 - 21:45',
  },
  {
    'site': 'MDW',
    'name': '60+ £1 Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Wednesday',
    'time': '06:30 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Wednesday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Wednesday',
    'time': '06:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Wednesday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Wednesday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Wednesday',
    'time': '13:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Wednesday',
    'time': '15:00 - 15:30',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Wednesday',
    'time': '15:35 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Juniors £1 swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Wednesday',
    'time': '16:00 - 18:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Wednesday',
    'time': '16:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Wednesday',
    'time': '16:00 - 19:35',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Wednesday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Calm Waters (Ladies)',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Wednesday',
    'time': '20:00 - 21:00',
  },
  {
    'site': 'MDW',
    'name': '2 Lane Triathlon',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Wednesday',
    'time': '21:00 - 22:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Wednesday',
    'time': '21:00 - 22:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Thursday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '06:30 - 08:00',
  },
  {
    'site': 'MDW',
    'name': 'Calm Waters',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '08:00 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '09:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Thursday',
    'time': '09:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': '60+ £1 Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Thursday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '13:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Thursday',
    'time': '15:00 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Thursday',
    'time': '16:00 - 18:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Thursday',
    'time': '16:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Thursday',
    'time': '16:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Bootle and North Swim Club',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Thursday',
    'time': '19:00 - 21:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Main pool',
    'day': 'Thursday',
    'time': '21:00 - 22:00',
  },
  {
    'site': 'MDW',
    'name': '60+ £1 Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Friday',
    'time': '06:30 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Friday',
    'time': '06:30 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Friday',
    'time': '06:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Friday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Fit',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Friday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Friday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Friday',
    'time': '13:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Friday',
    'time': '15:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Friday',
    'time': '15:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool **50% discount Friday Night Swim & Splash**',
    'day': 'Friday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Main Pool **50% discount Friday Night Swim & Splash**',
    'day': 'Friday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': '2 Lane Triathlon',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Friday',
    'time': '20:00 - 21:00',
  },
  {
    'site': 'MDW',
    'name': 'Adults Only',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Friday',
    'time': '20:00 - 21:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Saturday',
    'time': '08:30 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Saturday',
    'time': '08:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Saturday',
    'time': '08:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': '3 Lane Lifesaving Club',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Saturday',
    'time': '11:30 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Saturday',
    'time': '12:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Saturday',
    'time': '15:00 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Saturday',
    'time': '15:00 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Sunday',
    'time': '08:30 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Sunday',
    'time': '08:30 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Sunday',
    'time': '10:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Public Swim',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Sunday',
    'time': '10:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim Lessons',
    'type': 'pool',
    'info': 'Half of Main Pool',
    'day': 'Sunday',
    'time': '10:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Sunday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Swim & Splash',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Sunday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Juniors £1 swim',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Sunday',
    'time': '14:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Juniors £1 swim',
    'type': 'pool',
    'info': 'Learner Pool',
    'day': 'Sunday',
    'time': '14:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Bootle and North Swim Club',
    'type': 'pool',
    'info': 'Main Pool',
    'day': 'Sunday',
    'time': '15:15 - 17:15',
  },
];
