List eventsList = [
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'monday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'monday',
    'time': '07:30 - 08:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '08:15 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Aerobics',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Chair based circuit',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '11:30 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '11:30 - 12:15',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '12:00 - 12:45',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Relax and Revive',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '13:30 - 14:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '14:15 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'monday',
    'time': '16:15 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'monday',
    'time': '17:00 - 17:30',
  },
  {
    'site': 'MDW',
    'name': 'Cardio Kick',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '18:30 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Boxercise',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '19:00 - 19:45',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '19:50 - 20:20',
  },
  {
    'site': 'MDW',
    'name': 'HIIT',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '20:00 - 20:45',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'monday',
    'time': '20:30 - 21:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'tuesday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'tuesday',
    'time': '07:45 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '08:45 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '10:30 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '13:15 - 14:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '14:30 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '15:15 - 16:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '15:30 - 16:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'tuesday',
    'time': '16:30 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '17:15 - 17:45',
  },
  {
    'site': 'MDW',
    'name': 'Booty Build',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '18:00 - 18:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '18:00 - 19:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Legs, Bums & Tums',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '19:30 - 20:15',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '19:30 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '20:00 - 20:45',
  },
  {
    'site': 'MDW',
    'name': 'HIIT',
    'type': 'class',
    'info': '',
    'day': 'tuesday',
    'time': '20:15 - 21:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'tuesday',
    'time': '21:15 - 21:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'wednesday',
    'time': '06:45 - 07:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual Sprint',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'wednesday',
    'time': '07:00 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '08:00 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '08:30 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Abs Blast',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '11:30 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '12:15 - 13:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '13:30 - 14:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '14:30 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '15:45 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'wednesday',
    'time': '16:30 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'wednesday',
    'time': '17:15 - 17:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Boxercise',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '19:00 - 19:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '19:30 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Dance Fit',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '19:45 - 20:30',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'wednesday',
    'time': '20:30 - 21:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'thursday',
    'time': '06:45 - 07:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'thursday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '08:00 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual Sprint',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '08:00 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '09:15 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '10:15 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Zumba',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Padwork Circuit',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '11:15 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Relax and Revive',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '12:15 - 13:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '13:15 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '14:30 - 15:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'thursday',
    'time': '16:15 - 17:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '18:00 - 18:30',
  },
  {
    'site': 'MDW',
    'name': 'Cardio Kick',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '18:45 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '19:00 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit',
    'type': 'class',
    'info': '',
    'day': 'thursday',
    'time': '19:30 - 20:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'thursday',
    'time': '20:20 - 21:05',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'thursday',
    'time': '21:10 - 21:40',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'friday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'friday',
    'time': '06:45 - 07:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'friday',
    'time': '07:45 - 08:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '07:45 - 08:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '08:45 - 09:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '09:25 - 10:25',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '09:30 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Spin',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '10:30 - 11:15',
  },
  {
    'site': 'MDW',
    'name': 'Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '10:30 - 11:30',
  },
  {
    'site': 'MDW',
    'name': 'Total Tone',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '11:30 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Aqua Aerobics',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '12:00 - 13:00',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '12:30 - 13:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '13:45 - 14:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '14:45 - 15:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '15:45 - 16:45',
  },
  {
    'site': 'MDW',
    'name': 'Pilates',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '17:00 - 18:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '18:00 - 18:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '19:00 - 19:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills CXWorx',
    'type': 'class',
    'info': '',
    'day': 'friday',
    'time': '19:30 - 20:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'friday',
    'time': '20:40 - 21:10',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'saturday',
    'time': '08:15 - 09:00',
  },
  {
    'site': 'MDW',
    'name': 'Advanced Tai Chi',
    'type': 'class',
    'info': '',
    'day': 'saturday',
    'time': '09:00 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit Strength',
    'type': 'class',
    'info': '',
    'day': 'saturday',
    'time': '09:15 - 09:45',
  },
  {
    'site': 'MDW',
    'name': 'Baby Ballet',
    'type': 'class',
    'info': '',
    'day': 'saturday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Sprint',
    'type': 'class',
    'info': '',
    'day': 'saturday',
    'time': '10:00 - 10:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Grit Plyo',
    'type': 'class',
    'info': '',
    'day': 'saturday',
    'time': '10:35 - 11:05',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'saturday',
    'time': '11:30 - 12:15',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'saturday',
    'time': '13:00 - 14:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'saturday',
    'time': '14:00 - 15:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'saturday',
    'time': '15:30 - 16:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Combat Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '09:00 - 10:00',
  },
  {
    'site': 'MDW',
    'name': 'Yoga',
    'type': 'class',
    'info': '',
    'day': 'sunday',
    'time': '10:00 - 11:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump',
    'type': 'class',
    'info': '',
    'day': 'sunday',
    'time': '11:00 - 12:00',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills RPM Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '11:45 - 12:30',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Pump Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '12:45 - 13:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills The Trip',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '13:00 - 13:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills ShBam Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '14:00 - 14:45',
  },
  {
    'site': 'MDW',
    'name': 'Les Mills Body Balance Virtual',
    'type': 'class',
    'info': 'Youth Applicable',
    'day': 'sunday',
    'time': '15:00 - 16:00',
  },
];
